@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzU4ODM4OTl9.m6J7FSbrUwKkOaM2CXlAxDsA3Qg5DOxVNnVn8EDXKho

### Recipes Index
GET http://localhost:3000/recipes

### Recipes Show
GET http://localhost:3000/recipes/14
# Authorization: Bearer {{jwt}}
###

POST http://localhost:3000/recipes
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "title": "Green Eggs and Ham",
  "ingredients": "Green Eggs, Ham",
  "directions": "I don't actually want them",
  "prep_time": 15
}

###

PATCH http://localhost:3000/recipes/10
Content-Type: application/json

{
  "prep_time": 30
}

###

DELETE http://localhost:3000/recipes/9

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Zia",
  "email": "zia@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}


### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "ace@gmail.com",
  "password": "password"
}

### Messages Index
GET http://localhost:3000/messages

### Messages Create
POST http://localhost:3000/messages
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "body": "I am the best cat in the house"
}
